version: '3.9'

services:
  portfolio-backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    expose:
      - 80
    environment:
      ASPNETCORE_ENVIRONMENT: Development  

  portfolio-frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    depends_on:
      - portfolio-backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - portfolio-frontend
      - portfolio-backend
