version: '3.9'

services:
  # nginx reverse proxy    
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs 
      - ./vhost:/etc/nginx/vhost.d 
      - ./html:/usr/share/nginx/html 
      
  # reverse proxy let's encrypt companion
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
        - DEFAULT_EMAIL=kylelewis@rogers.com
    depends_on:
      - nginx-proxy

  portfolio-backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      VIRTUAL_HOST: backend.kodewithkyle.net
      LETSENCRYPT_HOST: backend.kodewithkyle.net
      LETSENCRYPT_EMAIL: kylelewis@rogers.com

  portfolio-frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: kodewithkyle.net
      LETSENCRYPT_HOST: kodewithkyle.net
      LETSENCRYPT_EMAIL: kylelewis@rogers.com
    depends_on:
      - portfolio-backend

  