version: '3.9'

services:
  portfolio-backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      VIRTUAL_HOST: backend.kodewithkyle.net
      LETSENCRYPT_HOST: backend.kodewithkyle.net
      LETSENCRYPT_EMAIL: kylelewis@rogers.com
    networks:
      - proxy-tier

  portfolio-frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: kodewithkyle.net
      LETSENCRYPT_HOST: kodewithkyle.net
      LETSENCRYPT_EMAIL: kylelewis@rogers.com
    depends_on:
      - portfolio-backend
    networks:
      - proxy-tier

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    restart: always
    environment:
      - DEFAULT_HOST=kodewithkyle.net
    networks:
      - proxy-tier
    labels:
      - com.github.nginx-proxy.docker-gen

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy
    networks:
      - proxy-tier

networks:
  proxy-tier:
