version: '3.9'

services:
  portfolio-backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      VIRTUAL_HOST: backend.kodewithkyle.net
      LETSENCRYPT_HOST: backend.kodewithkyle.net
      LETSENCRYPT_EMAIL: your-email@example.com

  portfolio-frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: kodewithkyle.net
      LETSENCRYPT_HOST: kodewithkyle.net
      LETSENCRYPT_EMAIL: your-email@example.com
    depends_on:
      - portfolio-backend

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    restart: always
    depends_on:
      - nginx-proxy
