name: Deploy to EC2

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-main
      cancel-in-progress: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no deployer@ec2-15-156-120-62.ca-central-1.compute.amazonaws.com << 'EOF'
          cd Portfolio/
          git pull
          docker-compose up -d --build
        EOF
